'''
Generated by GPT with prompt: create a python script for a gui that records 1 second of audio
and saves as a file using f'heyditto-int(time.time()).wav' as file name with a start recording
button and save file button. 
'''

import pyaudio
import wave
import time
import tkinter as tk


def record_audio():
    # create pyaudio object
    CHUNK = 8000
    FORMAT = pyaudio.paInt16
    CHANNELS = 1
    RATE = 16000
    RECORD_SECONDS = 1
    # WAVE_OUTPUT_FILENAME = f"heyditto-{int(time.time())}.wav"
    WAVE_OUTPUT_FILENAME = f"background-{int(time.time())}.wav"

    p = pyaudio.PyAudio()

    stream = p.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=RATE,
                    input=True,
                    frames_per_buffer=CHUNK)

    print("* recording")

    frames = []

    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        frames.append(data)

    print("* done recording")

    stream.stop_stream()
    stream.close()
    p.terminate()

    wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
    wf.setnchannels(CHANNELS)
    wf.setsampwidth(p.get_sample_size(FORMAT))
    wf.setframerate(RATE)
    wf.writeframes(b''.join(frames))
    wf.close()


# create window object
window = tk.Tk()
window.title('Audio Recorder')

# create start recording button
start_recording_button = tk.Button(window, text='Start Recording', command=record_audio)
start_recording_button.pack()

# create save file button
save_file_button = tk.Button(window, text='Save File')
save_file_button.pack()

window.mainloop()